### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Leael** [parkpow/deep-license-plate-recognition#177]
I'm having trouble figuring out how to download snapshot images using your API. I've reviewed the documentation, but I'm still unclear on the exact steps or endpoints to use for this purpose.

**Comment by danleyb2** [comment]
@Leael Trouble with downloading Docker images or pictures? Response when you run recognition is a JSON and not an image

**Comment by Leael** [comment]
@danleyb2 I need to download the raw images and json

**Comment by danleyb2** [comment]
@Leael 
Which raw image do you need to download?  Kindly share where you got info or hint about downloading raw images?
Feel free to send me a message on Skype at bondieki for quicker feedback

**Comment by Leael** [comment]
@danleyb2 nvm. I've got what I want  using webhooks. Thank you
